name: manikoth
favicon: null
layout_spectrum: 0.9214801301714033
typography_spectrum: 0.35977579187601805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
